export enum ANSWER_STATUS_ENUM {
  NORMAL = 'NORMAL',
  DELETED = 'DELETED',
}

export enum ANSWER_TYPE_ENUM {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
}

export enum ANSWER_HINT_TYPE_ENUM {
  NONE = 'NONE',
  IMAGE = 'IMAGE',
  ARTICLE = 'ARTICLE',
  VIDEO = 'VIDEO',
}
