export enum GAME_STATUS_ENUM {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  DELETED = 'DELETED',
}

export enum GAME_PLAYER_AGENT_MODE {
  NONE = 'NONE',
  WEB_ONLY = 'WEB_ONLY',
  APP_ONLY = 'APP_ONLY',
}

export enum GAME_PLAYER_AUTH_MODE {
  NONE = 'NONE',
  ALL_MEMBER = 'ALL_MEMBER',
  PHONE_MEMBER = 'PHONE_MEMBER',
}

export enum GAME_REWARD_TYPE {
  RANK = 'RANK',
  LOTTERY = 'LOTTERY',
}
